### ISSUE TITLE
Создание логотипа

### ISSUE THREAD

**Issue by Tenchyga** [Tenchyga/something#23]
### Актуальность
Логотип необходимо создать, так как при работе приложения можно заметить логотип, вставляемый PyQT5 по умолчанию буквально на все.

### Задача
Создать простой, приятный для глаза, но в то же время подходящий к приложению логотип. Это добавит косметического эффекта в виде серьезности и намеренности приложения.

- [x] Логотип создан и передан техлиду

**Comment by Bokalysha** [comment]
**Логотип** был разработан ссылаясь на символ Сибирского Федерального Университета, то есть белку с использованием цветов из будущего приложения, которые в свою очередь используются самим университетом.
![image](https://user-images.githubusercontent.com/95741454/166403352-d447c11c-6dac-4f5a-a1e9-856e2ae22227.png)

**Comment by Bokalysha** [comment]
За **логотип** на панель задач был взят символ СФУ.
![image](https://user-images.githubusercontent.com/95741454/166403534-23975178-7dd0-4531-8437-b5e3b331254f.png)
